apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus          # cố định để dashboard tham chiếu được
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
